### ISSUE TITLE
Faced two problems

### ISSUE THREAD

**Issue by hemnf** [knowledgetechnologyuhh/EmotionRecognitionBarros#1]
Dear Dr. Barros,
Thank you for your code. I faced two problems:

1. In CategoricaModel, you wrote the directions as a     
`modelDirectory = "/data/code/Vision-Models/Vision Models/EmotionRecognition_Vision_FrameBased/Trained Networks/Vision/FER2013Plus_Augmented_CNN/Model/CNN.h5"`
But I think the CNN file is in another directory. Is it right?

2. When I want to run run.py file, it shows me this error:
```
 File "/usr/local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 230, in func_load
    raw_code = codecs.decode(code.encode('ascii'), 'base64')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 81-84: ordinal not in range(128)
```

Any idea?

Thanks

**Comment by pablovin** [comment]
Hey, 

Thanks for the message!

For 1) you are right, I corrected the path now and it should work properly.

for 2 could be because you are trying to run this on python 3, and the demo should run on python 2. Let me know if this helps!

**Comment by hemnf** [comment]
Dear Dr.
Thank you for your reply. Do you use python 2.0? Because I have the same error in python 2.7 too.
Kind regards

**Comment by pablovin** [comment]
Hey,

So, the code is to be used with python 2.7. This error looks like something on Keras itself and related to python 3.6:

" File "/usr/local/lib/python3.6/site-packages/keras/utils/generic_utils.py","

 Make sure that you are running the code on python 2.7, and please copy here the error and the line the error happens.
